apiVersion: 1

datasources:
  - name: InfluxDB-DHSILED
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: dhsiled
      defaultBucket: crowd_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: dhsiled-super-secret-token-2024
    isDefault: true
    editable: true