version: '3.8'

services:
  # ============================================================================
  # InfluxDB - Time Series Database
  # ============================================================================
  influxdb:
    image: influxdb:2.7
    container_name: dhsiled-influxdb
    restart: unless-stopped
    
    ports:
      - "8086:8086"
    
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: dhsiled_admin
      DOCKER_INFLUXDB_INIT_PASSWORD: dhsiled_secure_2024
      DOCKER_INFLUXDB_INIT_ORG: dhsiled
      DOCKER_INFLUXDB_INIT_BUCKET: crowd_metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dhsiled-super-secret-token-2024
    
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
      - ./config/influxdb.conf:/etc/influxdb2/influxdb.conf:ro
    
    networks:
      - dhsiled-network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================================================
  # Grafana - Visualization Platform
  # ============================================================================
  grafana:
    image: grafana/grafana:10.2.0
    container_name: dhsiled-grafana
    restart: unless-stopped
    
    ports:
      - "3001:3000"
    
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-clock-panel
      GF_SERVER_ROOT_URL: http://localhost:3001
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    
    depends_on:
      influxdb:
        condition: service_healthy
    
    networks:
      - dhsiled-network
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

# ============================================================================
# Networks
# ============================================================================
networks:
  dhsiled-network:
    driver: bridge

# ============================================================================
# Volumes
# ============================================================================
volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana-data:
    driver: local