# ============================================================================
# DHSILED Central Services Deployment
# Backend, WebSocket, Ditto Bridge, and Frontend
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: dhsiled
  labels:
    name: dhsiled

---
# ============================================================================
# MQTT Broker (Mosquitto)
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: dhsiled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: websocket
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
        - name: data
          mountPath: /mosquitto/data
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: dhsiled
spec:
  type: ClusterIP
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 9001
    targetPort: 9001
    name: websocket
  selector:
    app: mosquitto

---
# ============================================================================
# MongoDB Database
# ============================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dhsiled
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: dhsiled
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dhsiled
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
# ============================================================================
# Backend API Server
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dhsiled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dhsiled/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MQTT_HOST
          value: "mosquitto"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/dhsiled"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dhsiled
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend

---
# ============================================================================
# WebSocket Server
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: dhsiled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: dhsiled/websocket:latest
        ports:
        - containerPort: 8080
        env:
        - name: MQTT_HOST
          value: "mosquitto"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: dhsiled
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: websocket

---
# ============================================================================
# Ditto Bridge
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ditto-bridge
  namespace: dhsiled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ditto-bridge
  template:
    metadata:
      labels:
        app: ditto-bridge
    spec:
      containers:
      - name: ditto-bridge
        image: dhsiled/ditto-bridge:latest
        env:
        - name: MQTT_HOST
          value: "mosquitto"
        - name: DITTO_HOST
          value: "ditto-gateway"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
# ============================================================================
# Command Center (Frontend)
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-center
  namespace: dhsiled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: command-center
  template:
    metadata:
      labels:
        app: command-center
    spec:
      containers:
      - name: command-center
        image: dhsiled/command-center:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: command-center
  namespace: dhsiled
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: command-center

---
# ============================================================================
# Ingress for External Access
# ============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dhsiled-ingress
  namespace: dhsiled
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: dhsiled.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: command-center
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: websocket
            port:
              number: 8080
  tls:
  - hosts:
    - dhsiled.example.com
    secretName: dhsiled-tls

---
# ============================================================================
# Secrets
# ============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dhsiled
type: Opaque
stringData:
  username: dhsiled_admin
  password: dhsiled_secure_2024

---
# ============================================================================
# ConfigMap for Mosquitto
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: dhsiled
data:
  mosquitto.conf: |
    listener 1883
    protocol mqtt
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/

---
# ============================================================================
# PersistentVolumeClaims
# ============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: dhsiled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi