# ============================================================================
# Prometheus Configuration for DHSILED
# Monitoring configuration for all system components
# ============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dhsiled-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # ============================================================================
  # Prometheus Self Monitoring
  # ============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # ============================================================================
  # Edge Processors
  # ============================================================================
  - job_name: 'edge-processors'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - dhsiled
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: edge-processor
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: grid_id
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: '${1}:9090'

  # ============================================================================
  # Backend Services
  # ============================================================================
  - job_name: 'backend'
    kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
            - dhsiled
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: backend

  # ============================================================================
  # MQTT Broker
  # ============================================================================
  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto:9090']
        labels:
          service: 'mqtt-broker'

  # ============================================================================
  # MongoDB
  # ============================================================================
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          service: 'mongodb'

  # ============================================================================
  # Node Exporters (System Metrics)
  # ============================================================================
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__

  # ============================================================================
  # WebSocket Server
  # ============================================================================
  - job_name: 'websocket'
    kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
            - dhsiled
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: websocket

  # ============================================================================
  # Ditto Digital Twins
  # ============================================================================
  - job_name: 'ditto'
    static_configs:
      - targets: ['ditto-gateway:9095']
        labels:
          service: 'ditto'

  # ============================================================================
  # Kubernetes API Server
  # ============================================================================
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # ============================================================================
  # Kubernetes Pods
  # ============================================================================
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# ============================================================================
# Remote Write (Optional - for long-term storage)
# ============================================================================
# remote_write:
#   - url: "http://influxdb:8086/api/v1/prom/write?db=dhsiled"