---
# ============================================================================
# DHSILED Raspberry Pi Setup Playbook
# Configures Raspberry Pi for edge computing
# ============================================================================

- name: Setup Raspberry Pi for DHSILED Edge Computing
  hosts: raspberry_pi
  become: yes
  
  vars:
    python_version: "3.10"
    grid_id: "G01"
    mqtt_broker: "192.168.1.100"
    
  tasks:
    # ==========================================================================
    # System Update
    # ==========================================================================
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        
    # ==========================================================================
    # Install System Dependencies
    # ==========================================================================
    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - python3-opencv
          - libopencv-dev
          - libatlas-base-dev
          - libhdf5-dev
          - git
          - wget
          - curl
          - vim
          - htop
        state: present
        
    # ==========================================================================
    # Configure Camera
    # ==========================================================================
    - name: Enable camera interface
      lineinfile:
        path: /boot/config.txt
        regexp: '^#?start_x='
        line: 'start_x=1'
        
    - name: Set GPU memory
      lineinfile:
        path: /boot/config.txt
        regexp: '^#?gpu_mem='
        line: 'gpu_mem=128'
        
    # ==========================================================================
    # Create Application Directory
    # ==========================================================================
    - name: Create DHSILED directory
      file:
        path: /opt/dhsiled
        state: directory
        owner: pi
        group: pi
        mode: '0755'
        
    - name: Create data directories
      file:
        path: "{{ item }}"
        state: directory
        owner: pi
        group: pi
        mode: '0755'
      loop:
        - /opt/dhsiled/data
        - /opt/dhsiled/data/logs
        - /opt/dhsiled/data/video_buffer
        - /opt/dhsiled/models
        
    # ==========================================================================
    # Copy Application Files
    # ==========================================================================
    - name: Copy edge computing application
      synchronize:
        src: ../../edge-computing/
        dest: /opt/dhsiled/
        rsync_opts:
          - "--exclude=*.pyc"
          - "--exclude=__pycache__"
          - "--exclude=data/*"
          
    # ==========================================================================
    # Install Python Dependencies
    # ==========================================================================
    - name: Install Python requirements
      pip:
        requirements: /opt/dhsiled/requirements.txt
        executable: pip3
        extra_args: --no-cache-dir
      become_user: pi
      
    # ==========================================================================
    # Configure Grid Settings
    # ==========================================================================
    - name: Update grid configuration
      template:
        src: templates/grid_config.yaml.j2
        dest: /opt/dhsiled/config/grid_config.yaml
        owner: pi
        group: pi
        mode: '0644'
        
    # ==========================================================================
    # Create Systemd Service
    # ==========================================================================
    - name: Create systemd service file
      template:
        src: templates/dhsiled-edge.service.j2
        dest: /etc/systemd/system/dhsiled-edge.service
        owner: root
        group: root
        mode: '0644'
        
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        
    - name: Enable DHSILED edge service
      systemd:
        name: dhsiled-edge
        enabled: yes
        
    # ==========================================================================
    # Configure Monitoring
    # ==========================================================================
    - name: Install system monitoring tools
      apt:
        name:
          - sysstat
          - iotop
        state: present
        
    # ==========================================================================
    # Setup Log Rotation
    # ==========================================================================
    - name: Configure logrotate for DHSILED
      copy:
        dest: /etc/logrotate.d/dhsiled
        content: |
          /opt/dhsiled/data/logs/*.log {
              daily
              rotate 7
              compress
              delaycompress
              missingok
              notifempty
              create 0644 pi pi
          }
        owner: root
        group: root
        mode: '0644'
        
    # ==========================================================================
    # Final Steps
    # ==========================================================================
    - name: Display completion message
      debug:
        msg: |
          ============================================
          DHSILED Edge Setup Complete!
          ============================================
          Grid ID: {{ grid_id }}
          MQTT Broker: {{ mqtt_broker }}
          
          To start the service:
          sudo systemctl start dhsiled-edge
          
          To check status:
          sudo systemctl status dhsiled-edge
          
          To view logs:
          journalctl -u dhsiled-edge -f
          ============================================